<?php
$config['mail.transport'] = 'default';
$config['mail.from'] = array('test@test.com' => 'Virtual Scrum Meetings');
$config['colors'] = array(
    'red',
    'purple',
    'blue',
    'cyan',
    'green',
    'lime',
    'amber',
    'deep-orange',
    'brown',
    'pink',
    'red darken-4',
    'purple darken-4',
    'blue darken-4',
    'cyan darken-4',
    'green darken-4',
    'lime darken-4',
    'amber darken-4',
    'deep-orange darken-4',
    'brown darken-4',
    'pink darken-4',
    'red lighten-4',
    'purple lighten-4',
    'blue lighten-4',
    'cyan lighten-4',
    'green lighten-4',
    'lime lighten-4',
    'amber lighten-4',
    'deep-orange lighten-4',
    'brown lighten-4',
    'pink lighten-4',
    'blue-grey'
);